"""
Module 2 — Step 4: IGRF removal.

The International Geomagnetic Reference Field (IGRF) is a mathematical model of
Earth's main magnetic field, generated by electric currents in the liquid outer core.
It accounts for ~99% of the total measured field (~59 000 nT in Mongolia). Removing
it leaves only the residual anomaly caused by crustal magnetisation — the geological
signal of interest.

The IGRF is computed at each sample point using its geographic coordinates and altitude,
and is evaluated for the exact date of the flight (the field drifts ~100 nT/year due to
secular variation).

Formula
-------
    F_IGRF(lon, lat, h, t) = sqrt(Be² + Bn² + Bu²)    [total intensity, nT]
    Mag1_IGRF = Mag1_Diurnal − F_IGRF

where:
    Be, Bn, Bu  : East, North, Up field components from IGRF-13 model (nT)
    Mag1_Diurnal: field after diurnal correction (step 3)
    h           : ellipsoidal height from GPS (km)
    t           : UTC date of the flight

Library: ppigrf (https://github.com/klaundal/ppigrf)
    pip install ppigrf

In Oasis Montaj this step is done under
Process → IGRF → Remove IGRF.
"""

from datetime import datetime

import numpy as np
import pandas as pd
import ppigrf


def date_from_folder(date_str: str) -> datetime:
    """
    Parse a flight date folder name (DD.MM.YYYY) to a datetime object.

    Parameters
    ----------
    date_str : e.g. '22.04.2022'
    """
    return datetime.strptime(date_str, '%d.%m.%Y')


def compute_igrf(
    lon: np.ndarray,
    lat: np.ndarray,
    alt_m: np.ndarray,
    date: datetime,
) -> np.ndarray:
    """
    Compute IGRF-13 total field intensity at each sample point.

    Parameters
    ----------
    lon   : longitude array (degrees)
    lat   : latitude array (degrees)
    alt_m : ellipsoidal height from GPS (metres); NaN values are replaced by
            the column median before computation
    date  : UTC date of the flight

    Returns
    -------
    F_igrf : total field intensity array (nT), same length as input
    """
    alt_km = np.where(np.isfinite(alt_m), alt_m, np.nanmedian(alt_m)) / 1000.0

    Be, Bn, Bu = ppigrf.igrf(lon, lat, alt_km, date)
    F = np.sqrt(np.asarray(Be)**2 + np.asarray(Bn)**2 + np.asarray(Bu)**2)
    return F.flatten()


def apply_igrf(df: pd.DataFrame, date_str: str) -> pd.DataFrame:
    """
    Remove the IGRF reference field from Mag1_Diurnal and Mag2_Diurnal.

    Adds columns:
        IGRF        : IGRF total intensity at each sample point (nT)
        Mag1_IGRF   : Mag1_Diurnal minus IGRF  →  residual anomaly (nT)
        Mag2_IGRF   : Mag2_Diurnal minus IGRF  →  residual anomaly (nT)

    Parameters
    ----------
    df       : flight DataFrame with Xgps, Ygps, Zgps, Mag1_Diurnal, Mag2_Diurnal
    date_str : flight date folder name (DD.MM.YYYY)
    """
    df   = df.copy()
    date = date_from_folder(date_str)

    lon   = df['Xgps'].values
    lat   = df['Ygps'].values
    alt_m = df['Zgps'].values if 'Zgps' in df.columns else np.full(len(df), 100.0)

    F_igrf = compute_igrf(lon, lat, alt_m, date)
    df['IGRF'] = F_igrf

    if 'Mag1_Diurnal' in df.columns:
        df['Mag1_IGRF'] = df['Mag1_Diurnal'] - F_igrf
    if 'Mag2_Diurnal' in df.columns:
        df['Mag2_IGRF'] = df['Mag2_Diurnal'] - F_igrf

    f_mean  = float(np.nanmean(F_igrf))
    f_range = float(np.nanmax(F_igrf) - np.nanmin(F_igrf))
    print(f"  [IGRF] Date: {date.strftime('%Y-%m-%d')}  |  "
          f"F mean: {f_mean:.1f} nT  |  "
          f"spatial range: {f_range:.2f} nT")

    return df
